const path = require("path")
console.log(path.dirname('C:/Users/dell/OneDrive/Desktop/Nodejs/path.js'))
console.log(path.extname('C:/Users/dell/OneDrive/Desktop/Nodejs/path.js'))
console.log(path.basename('C:/Users/dell/OneDrive/Desktop/Nodejs/path.js'))
console.log(path.parse('C:/Users/dell/OneDrive/Desktop/Nodejs/path.js'))
